1431

diff --git a/init.d-disable/S70zmqfwd b/init.d-disable/S70zmqfwd
--- a/init.d-disable/S70zmqfwd
+++ b/init.d-disable/S70zmqfwd
@@ -2,37 +2,35 @@
 
 # APPLICATION
 NAME="ZMQ forwarder"
-DAEMON="zmq_forwarder.py"
-DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
-DAEMON_OPTS=""
-
-if [ -x $DAEMON_PATH/$DAEMON ]; then
-  echo "Can't execute $DAEMON_PATH/$DAEMON"
-  exit 1
-fi
-
-retval=0
-
 # PID (created by start-stop-daemon -m)
-PIDFILE=/var/run/$DAEMON.pid
+PID="zmq_forwarder"
+PID_FILE=/var/run/$PID.pid
+DAEMON="zmq_forwarder.py"
+DAEMON_OPTS=""
+DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
+DAEMON_FILE=$DAEMON_PATH/$DAEMON
+
+RETVAL=0
 
 start() {
-        if [ -f $DAEMON_PATH/$DAEMON ]; then
-          echo "Starting $NAME..."
-          start-stop-daemon -b -x $DAEMON_PATH/$DAEMON -m -p $PIDFILE -S -- $DAEMON_OPTS
-          retval=$?
-		else
-          echo "$DAEMON not found!"
-        fi
+    if [ -f $DAEMON_FILE ]; then
+        echo "Starting $NAME..."
+        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
+        RETVAL=$?
+    else
+	    RETVAL=-1
+        echo "$DAEMON not found!"
+    fi
 }
 
 stop() {
         echo "Stopping $NAME"
-        start-stop-daemon -p $PIDFILE -K
-        retval=$?
+        start-stop-daemon -p $PID_FILE -K
+        RETVAL=$?
 		# --remove-pidfile not supported by busybox
-        if [ -f $PIDFILE ]; then
-            rm -f $PIDFILE
+		#[ $RETVAL = 0 ] && rm -f $PID_FILE
+        if [ -f $PID_FILE ]; then
+            rm -f $PID_FILE
         fi
 }
 
@@ -52,4 +50,11 @@ case "$1" in
         exit 1
 esac
 
-exit $retval
+# Print OK/FAIL
+if [ $RETVAL -eq 0 ]; then
+    echo "[ OK ]"
+else
+    echo "[FAIL]"
+fi
+
+exit $RETVAL
