1352

diff --git a/init.d-disable/S70zmqfwd b/init.d-disable/S70zmqfwd
--- a/init.d-disable/S70zmqfwd
+++ b/init.d-disable/S70zmqfwd
@@ -6,7 +6,10 @@ DAEMON="d_zmq_forwarder.py"
 DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
 DAEMON_OPTS=""
 
-[ -x $DAEMON ] || exit 1
+if [ -x $DAEMON_PATH/$DAEMON ]; then
+  echo "Can't execute $DAEMON_PATH/$DAEMON"
+  exit 1
+fi
 
 retval=0
 
@@ -16,7 +19,7 @@ PIDFILE=/var/run/$DAEMON.pid
 start() {
         if [ -f $DAEMON_PATH/$DAEMON ]; then
           echo "Starting $NAME..."
-          start-stop-daemon -b -x $DAEMON -m -p $PIDFILE -S -- $DAEMON_OPTS
+          start-stop-daemon -b -x $DAEMON_PATH/$DAEMON -m -p $PIDFILE -S -- $DAEMON_OPTS
           retval=$?
 		else
           echo "$DAEMON not found!"
