1451

diff --git a/init.d-disable/S71ads1x15 b/init.d-disable/S71ads1x15
--- a/init.d-disable/S71ads1x15
+++ b/init.d-disable/S71ads1x15
@@ -1,30 +1,38 @@
 #!/bin/sh
 
 # APPLICATION
-NAME="dBus MPD helper"
-DAEMON="/mnt/PIHU_APP/defender-headunit/plugins/control/d_dbus_ads1x15.py"
-DAEMONOPTS=""
+#DAEMON="/mnt/PIHU_APP/defender-headunit/plugins/control/d_dbus_ads1x15.py"
 
-# PID (created by application)
-PIDFILE=/var/run/dbusads.pid
+NAME="Remote Control: ADS1x15 Resistor Network"
+# PID (created by start-stop-daemon -m)
+PID="ctrl_ads1x15"
+PID_FILE=/var/run/$PID.pid
+DAEMON="control_ads1x15.py"
+DAEMON_OPTS=""
+DAEMON_PATH="/mnt/PIHU_APP/defender-headunit/daemons"
+DAEMON_FILE=$DAEMON_PATH/$DAEMON
+
+RETVAL=0
 
 start() {
-        if [ -f $DAEMON ]; then
-          echo "Starting $NAME..."
-          $DAEMON $DAEMONOPTS &
-        else
-          echo "$DAEMON not found!"
-        fi
+    if [ -f $DAEMON_FILE ]; then
+        echo "Starting $NAME..."
+        start-stop-daemon -b -x $DAEMON_FILE -m -p $PID_FILE -S -- $DAEMON_OPTS
+        RETVAL=$?
+    else
+	    RETVAL=-1
+        echo "$DAEMON not found!"
+    fi
 }
 
 stop() {
-        if [ -f $PIDFILE ]; then
-            echo "Stopping $NAME"
-            PID=`cat $PIDFILE`
-            kill -HUP $PID
-            rm -f $PIDFILE
-        else
-            echo "$PIDFILE not found, aborting..."
+        echo "Stopping $NAME"
+        start-stop-daemon -p $PID_FILE -K
+        RETVAL=$?
+		# --remove-pidfile not supported by busybox
+		#[ $RETVAL = 0 ] && rm -f $PID_FILE
+        if [ -f $PID_FILE ]; then
+            rm -f $PID_FILE
         fi
 }
 
@@ -44,4 +52,11 @@ case "$1" in
         exit 1
 esac
 
-exit $?
+# Print OK/FAIL
+if [ $RETVAL -eq 0 ]; then
+    echo "[ OK ]"
+else
+    echo "[FAIL]"
+fi
+
+exit $RETVAL
